### ISSUE TITLE
--analyze output not understandable.

### ISSUE THREAD

**Issue by Evi1M4chine** [mgorny/unsymlink-lib#1]
Hey, I’m, sadly, stuck with understanding what the “split“, “unowned”  and “pure” in the output of `--analyze` mean, and how to detect the “obvious” problems. I suspect I’m not the only one.

I’m sure it seemed really obvious, and I’m rather experienced with Gentoo, but I don’t know what to look for, and don’s want to migrate without this step.
All I can guess, is that “split” means the file is 32&64 bit, and “pure” means it’s only one of them. But … does “unowned” then mean it is not owned by any package and can probably be deleted? I don’t want to … guess. :)

An info on these terms in the README would probably solve the issue for many people. :)

**Comment by mgorny** [comment]
I'll look into replacing those short names with something more understandable, and then we'll see if they need additional documentation.

**Comment by mgorny** [comment]
So now we have the following messages:

```
directories that will be moved to /usr/lib/:
        tmpfiles.d
        gcc
        llvm
        portage
        systemd
        clang
        python-exec
        (+ 0 files)

directories whose contents will be split between /usr/lib/ and /usr/lib64/:

orphan files (not owned by any package) that will be moved to /usr/lib/:
        cracklib_dict.pwd
        cracklib_dict.pwi
        dri
        cracklib_dict.hwm
        libxslt-plugins
        ccache

orphan files (not owned by any package) that will be kept in /usr/lib64/:
        libdb_cxx.so
        libdb_sql.so
        libdb.a
        libdb_cxx.a
        libdb_stl.so
        libdb_sql.a
        libdb.so
```

Is that better? Do you think more explanation is necessary?

**Comment by ghost** [comment]
These're a lot better messages. I was also wondering what will happen to the unowned files and whether 
 can I remove them.

**Comment by mgorny** [comment]
(I'm making v13 with this change)
