### ISSUE TITLE
Allow to use hard links for space-limited systems

### ISSUE THREAD

**Issue by rbarrois** [mgorny/unsymlink-lib#10]
The current code uses `--reflink=auto` to enable copy-on-write on compatible filesystems — as of 2020-05, this seems to be mostly btrfs, ocfs, and xfs.

Space-constrained systems might fail (`/usr/lib64` can reach 7+ GB) when performing full copies; using hard links could avoid this.

This shouldn't cause any issue during the migration, as docs strongly discourage running emerge or modifying `/usr` before finishing the migration.

However, unexpected failures could occur if old files are kept around and modified after the migration; this might require "unlinking" the remaining (copied but not removed) files in the `--finish` step.

If this idea makes sense for the tool, I will gladly provide a pull-request for it — probably providing an opt-in command line flag to enable the feature.

**Comment by mgorny** [comment]
I suppose there's no harm in having that as an option. Please remember to copy at least one test for that variant.

**Comment by mgorny** [comment]
Fixed via #11.
