### ISSUE TITLE
.chk files

### ISSUE THREAD

**Issue by matijaskala** [mgorny/unsymlink-lib#2]
After running `unsymlink-lib --analyze`, the script wants to move `libsoftokn3.chk`, `libfreebl3.chk` and `libnssdbm3.chk` to `/usr/lib/`. These files are generated from the same-named `.so` libraries from `dev-libs/nss` and I think they belong to `lib64`.

**Comment by mgorny** [comment]
Where they come from? Can you think of any `*.chk` files that shouldn't be moved likewise?

**Comment by matijaskala** [comment]
nss ebuild creates them in `$(get_libdir)` which means lib64.
I searched debian package database for filenames ending with `.chk`. While libnss is not the only package that contains such files, it is the only package that installs them to `lib`.

**Comment by matijaskala** [comment]
They are not part of the ebuild. They are created during postinst phase because of stripped libraries.

**Comment by mgorny** [comment]
Thanks!
