### ISSUE TITLE
b'name' notation used in script output

### ISSUE THREAD

**Issue by ostroffjh** [mgorny/unsymlink-lib#4]
I just upgraded from 13 to 14, and now all the output uses the b'name' notation for file and directory names.  This is for both --analyze, and --migrate --pretend.  I'm no Python user, but a bit of searching suggests that if you use b'name' in the script, you need to do something before outputting it, or else the literal b'' will be included.  Is there any chance this is just due to some wayward configuration of my setup?

**Comment by ostroffjh** [comment]
I've played a bit, and found adding a .decode() to the item in the format() seems to work.  For --analyze, there are a few places after line 221, I can only assume similar is needed for the --migrate output.  (I have no idea if this is the right (i.e., Python) way to do this or not, but I think it confirms what the problem is.)

**Comment by mgorny** [comment]
It's intentional. I was considering making the output pretty but then it'd crash on 'invalid' filenames. And I really don't want it to crash ;-).

**Comment by ostroffjh** [comment]
As I'm not a Python user, at first I thought it was supposed to be some BOLD markup, but it's also in the output of --migrate, and bash isn't very happy with that.

**Comment by genterminl** [comment]
If I'm actually ready to migrate, should I revert to version 13 or wait for 15?

**Comment by mgorny** [comment]
This version works perfectly fine. Only the output is not exactly pretty but it should be readable enough.

**Comment by genterminl** [comment]
I'll test carefully later, but the output of --migrate --pretend also includes the b' ' notation, and I believe bash will choke on that.  Or does omitting the --pretend also drop the b' ' from the output?  If so, isn't that potentially dangerous, as the output might differ between with and without --pretend, where the only difference should be output vs output and passed to bash?

**Comment by mgorny** [comment]
The output is only meant for user-convenience (and bash-alikes are meant to shorter explain what will happen). All the work is either done directly from Python, or via correct subprocess calls.

**Comment by ostroffjh** [comment]
The actual conversion seems to have gone fine.  Should I close this, or leave it open as a reminder to fix the "pretty" output?
Separate question - in the --analyze output, some things listed as "files" are actually directories, and some things listed as "orphans" are not.  I suppose it's really just cosmetic, but I think it could seriously confuse at least some users.

**Comment by mgorny** [comment]
Let's keep it open and hopefully I won't forget to close it when I find time to fix it.

As for the 'files' issue, please report a separate bug and give me some more details.
