### ISSUE TITLE
script recognizes "lib64" but not "/usr/lib64" as proper symlink for /usr/lib

### ISSUE THREAD

**Issue by genterminl** [mgorny/unsymlink-lib#8]
Reported on the gentoo-user mailing list: unsymlink-lib --analyze quit with error (paraphrasing) "/usr/lib must be symlink to lib64" even though it was a symlink to /usr/lib64.  Different actual string, absolute vs relative, but same outcome (unless I miss something.)  The user ended up deleting and recreating the symlink to match what was expected, but would it be reasonable for the script to accept either?

**Comment by mgorny** [comment]
I suppose there should be no harm in allowing that. I'm considering if I could make it allow any form that actually points to the correct directory but I'm afraid this result in something unpredictable.
