### ISSUE TITLE
--analyze shows symbolic links as orphaned files

### ISSUE THREAD

**Issue by hrk** [mgorny/unsymlink-lib#9]
Running --analyze shows:
```
[...]
orphan dirs/files (not owned by any package) that will be kept in /usr/lib64/:
        libdb.a
        libdb.so
        libdb_cxx.a
        libdb_cxx.so
        libdb_sql.a
        libdb_sql.so
        libdb_stl.a
        libdb_stl.so
[... limiting to sys-libs/db files for simplicity]
 ```
These files, however, aren't man-made, they were the automated result of the installation of package(s):
 ```
argo-2 ~ # ls -lha /usr/lib64/libdb*
-rw-r--r-- 1 root root 3.0M Feb 12  2018 /usr/lib64/libdb-5.3.a
-rw-r--r-- 1 root root  926 Feb 12  2018 /usr/lib64/libdb-5.3.la
-rwxr-xr-x 1 root root 1.8M Feb 12  2018 /usr/lib64/libdb-5.3.so
lrwxrwxrwx 1 root root   11 Feb 12  2018 /usr/lib64/libdb.a -> libdb-5.3.a
-rw-r--r-- 1 root root 3.2M Feb 12  2018 /usr/lib64/libdb_cxx-5.3.a
-rw-r--r-- 1 root root  954 Feb 12  2018 /usr/lib64/libdb_cxx-5.3.la
-rwxr-xr-x 1 root root 1.9M Feb 12  2018 /usr/lib64/libdb_cxx-5.3.so
lrwxrwxrwx 1 root root   15 Feb 12  2018 /usr/lib64/libdb_cxx.a -> libdb_cxx-5.3.a
lrwxrwxrwx 1 root root   16 Feb 12  2018 /usr/lib64/libdb_cxx.so -> libdb_cxx-5.3.so
lrwxrwxrwx 1 root root   12 Feb 12  2018 /usr/lib64/libdb.so -> libdb-5.3.so
-rw-r--r-- 1 root root 3.7M Feb 12  2018 /usr/lib64/libdb_sql-5.3.a
-rw-r--r-- 1 root root  954 Feb 12  2018 /usr/lib64/libdb_sql-5.3.la
-rwxr-xr-x 1 root root 2.3M Feb 12  2018 /usr/lib64/libdb_sql-5.3.so
lrwxrwxrwx 1 root root   15 Feb 12  2018 /usr/lib64/libdb_sql.a -> libdb_sql-5.3.a
lrwxrwxrwx 1 root root   16 Feb 12  2018 /usr/lib64/libdb_sql.so -> libdb_sql-5.3.so
-rw-r--r-- 1 root root 3.4M Feb 12  2018 /usr/lib64/libdb_stl-5.3.a
-rw-r--r-- 1 root root  954 Feb 12  2018 /usr/lib64/libdb_stl-5.3.la
-rwxr-xr-x 1 root root 2.0M Feb 12  2018 /usr/lib64/libdb_stl-5.3.so
lrwxrwxrwx 1 root root   15 Feb 12  2018 /usr/lib64/libdb_stl.a -> libdb_stl-5.3.a
lrwxrwxrwx 1 root root   16 Feb 12  2018 /usr/lib64/libdb_stl.so -> libdb_stl-5.3.so
 ```
 ```
argo-2 ~ # qfile /usr/lib64/libdb*
sys-libs/db (/usr/lib64/libdb_sql-5.3.a)
sys-libs/db (/usr/lib64/libdb_stl-5.3.la)
sys-libs/db (/usr/lib64/libdb_sql-5.3.la)
sys-libs/db (/usr/lib64/libdb_stl-5.3.a)
sys-libs/db (/usr/lib64/libdb_cxx-5.3.so)
sys-libs/db (/usr/lib64/libdb-5.3.la)
sys-libs/db (/usr/lib64/libdb-5.3.so)
sys-libs/db (/usr/lib64/libdb_cxx-5.3.la)
sys-libs/db (/usr/lib64/libdb_cxx-5.3.a)
sys-libs/db (/usr/lib64/libdb_sql-5.3.so)
sys-libs/db (/usr/lib64/libdb-5.3.a)
sys-libs/db (/usr/lib64/libdb_stl-5.3.so)
 ```

Since the files aren't man-made, the output is confusing for users ("what should I do with those files?", "Is it right to migrate them there?").

The tool should not show them as orphaned and should handle them both in the output (they're not orphans) and by correctly migrating them to the right place (I am not saying they are't migrated correctly, as I lack the skill to understand the python code).

Thanks

**Comment by mgorny** [comment]
They might have been created by an ebuild but they were created directly on the live system rather than being installed and recorded, therefore they are orphaned. The tool has no way of knowing where they belong. It can guess, and it does that. It works in this case but there are no guarantees.

**Comment by hrk** [comment]
Thanks for the information.

Should I file a bug for each package that, in its last ebuild, creates such links rather than installing and recording them?

**Comment by hrk** [comment]
(FWIW I gave a look at the ebuild for db-5.3.28-r2 and can't see any links being created, maybe it's an issue in the used eclasses?)

**Comment by mgorny** [comment]
Yes, please file bugs if there isn't one open already. However, I'm afraid that I can't guarantee you that developers will take them seriously, or even consider it a bug. It's an old habit.

(I think db uses alternatives.eclass. That's another very old thing that was 'the way of the future', except it never were)
